// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: greet.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace GreetPackage {
  public static partial class GreetService
  {
    static readonly string __ServiceName = "greetPackage.GreetService";

    static readonly grpc::Marshaller<global::GreetPackage.GreetRequest> __Marshaller_greetPackage_GreetRequest = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GreetPackage.GreetRequest.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::GreetPackage.GreetResponse> __Marshaller_greetPackage_GreetResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::GreetPackage.GreetResponse.Parser.ParseFrom);

    static readonly grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> __Method_GreetUnary = new grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GreetUnary",
        __Marshaller_greetPackage_GreetRequest,
        __Marshaller_greetPackage_GreetResponse);

    static readonly grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> __Method_GreetServerStream = new grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GreetServerStream",
        __Marshaller_greetPackage_GreetRequest,
        __Marshaller_greetPackage_GreetResponse);

    static readonly grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> __Method_GreetClientStream = new grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(
        grpc::MethodType.ClientStreaming,
        __ServiceName,
        "GreetClientStream",
        __Marshaller_greetPackage_GreetRequest,
        __Marshaller_greetPackage_GreetResponse);

    static readonly grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> __Method_GreetFullStream = new grpc::Method<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(
        grpc::MethodType.DuplexStreaming,
        __ServiceName,
        "GreetFullStream",
        __Marshaller_greetPackage_GreetRequest,
        __Marshaller_greetPackage_GreetResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::GreetPackage.GreetReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of GreetService</summary>
    [grpc::BindServiceMethod(typeof(GreetService), "BindService")]
    public abstract partial class GreetServiceBase
    {
      /// <summary>
      ///Unary Service
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GreetPackage.GreetResponse> GreetUnary(global::GreetPackage.GreetRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Server Streaming Service
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GreetServerStream(global::GreetPackage.GreetRequest request, grpc::IServerStreamWriter<global::GreetPackage.GreetResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Client Streaming Service
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::GreetPackage.GreetResponse> GreetClientStream(grpc::IAsyncStreamReader<global::GreetPackage.GreetRequest> requestStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      ///Bi-Directional Streaming Service
      /// </summary>
      /// <param name="requestStream">Used for reading requests from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GreetFullStream(grpc::IAsyncStreamReader<global::GreetPackage.GreetRequest> requestStream, grpc::IServerStreamWriter<global::GreetPackage.GreetResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for GreetService</summary>
    public partial class GreetServiceClient : grpc::ClientBase<GreetServiceClient>
    {
      /// <summary>Creates a new client for GreetService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public GreetServiceClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for GreetService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public GreetServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected GreetServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected GreetServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      ///Unary Service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GreetPackage.GreetResponse GreetUnary(global::GreetPackage.GreetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GreetUnary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Unary Service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::GreetPackage.GreetResponse GreetUnary(global::GreetPackage.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GreetUnary, null, options, request);
      }
      /// <summary>
      ///Unary Service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GreetPackage.GreetResponse> GreetUnaryAsync(global::GreetPackage.GreetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GreetUnaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Unary Service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::GreetPackage.GreetResponse> GreetUnaryAsync(global::GreetPackage.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GreetUnary, null, options, request);
      }
      /// <summary>
      ///Server Streaming Service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::GreetPackage.GreetResponse> GreetServerStream(global::GreetPackage.GreetRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GreetServerStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Server Streaming Service
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::GreetPackage.GreetResponse> GreetServerStream(global::GreetPackage.GreetRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GreetServerStream, null, options, request);
      }
      /// <summary>
      ///Client Streaming Service
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> GreetClientStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GreetClientStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Client Streaming Service
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncClientStreamingCall<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> GreetClientStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncClientStreamingCall(__Method_GreetClientStream, null, options);
      }
      /// <summary>
      ///Bi-Directional Streaming Service
      /// </summary>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncDuplexStreamingCall<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> GreetFullStream(grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GreetFullStream(new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      ///Bi-Directional Streaming Service
      /// </summary>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncDuplexStreamingCall<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse> GreetFullStream(grpc::CallOptions options)
      {
        return CallInvoker.AsyncDuplexStreamingCall(__Method_GreetFullStream, null, options);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override GreetServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new GreetServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(GreetServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_GreetUnary, serviceImpl.GreetUnary)
          .AddMethod(__Method_GreetServerStream, serviceImpl.GreetServerStream)
          .AddMethod(__Method_GreetClientStream, serviceImpl.GreetClientStream)
          .AddMethod(__Method_GreetFullStream, serviceImpl.GreetFullStream).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, GreetServiceBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_GreetUnary, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(serviceImpl.GreetUnary));
      serviceBinder.AddMethod(__Method_GreetServerStream, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(serviceImpl.GreetServerStream));
      serviceBinder.AddMethod(__Method_GreetClientStream, serviceImpl == null ? null : new grpc::ClientStreamingServerMethod<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(serviceImpl.GreetClientStream));
      serviceBinder.AddMethod(__Method_GreetFullStream, serviceImpl == null ? null : new grpc::DuplexStreamingServerMethod<global::GreetPackage.GreetRequest, global::GreetPackage.GreetResponse>(serviceImpl.GreetFullStream));
    }

  }
}
#endregion
